/* Generated by AN DISI Unibo */ 
package it.unibo.soldstorageservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Soldstorageservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var capacity: Int =100  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outred("START")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t10",targetState="handleStore",cond=whenRequest("store"))
				}	 
				state("handleStore") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("store(N)"), Term.createTerm("store(K)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val load=payloadArg(0)  
								if(  capacity - load >0  
								 ){ capacity=capacity-load  
								answer("store", "store_accepted", "store_accepted(ok)"   )  
								}
								else
								 {answer("store", "store_rejected", "store_rejected(no_space)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="handleStore",cond=whenRequest("store"))
				}	 
			}
		}
} 
