/* Generated by AN DISI Unibo */ 
package it.unibo.blueled

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Blueled ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						CommUtils.outcyan("Blue Led OFF")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="onHandle",cond=whenDispatch("on"))
					transition(edgeName="t07",targetState="offHandle",cond=whenDispatch("off"))
				}	 
				state("onHandle") { //this:State
					action { //it:State
						CommUtils.outcyan("Blue Led ON")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="onHandle",cond=whenDispatch("on"))
					transition(edgeName="t09",targetState="offHandle",cond=whenDispatch("off"))
				}	 
				state("offHandle") { //this:State
					action { //it:State
						CommUtils.outcyan("Blue Led OFF")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="onHandle",cond=whenDispatch("on"))
					transition(edgeName="t011",targetState="offHandle",cond=whenDispatch("off"))
				}	 
			}
		}
} 
